# -*- coding: utf-8 -*-
"""dsbda8SK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oslTKlLxxkuvFC3ZfYlc0oEqyU4Df8JH
"""

import seaborn as sns
import matplotlib.pyplot as plt

#load the titanic
titanic = sns.load_dataset("titanic")

# 1. Visualizing patterns in the data
sns.set(style="whitegrid")
plt.figure(figsize=(12, 6))
sns.countplot(x='class', hue='survived', data=titanic, palette='Set1')
plt.title('Survival Count by Passenger Class')
plt.show()

# 2. Plotting a histogram for the distribution of ticket prices (fare)
plt.figure(figsize=(12, 6))

# Use Seaborn's histogram to visualize the distribution of ticket prices
sns.histplot(titanic['fare'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Ticket Prices (Fare)')
plt.xlabel('Fare')
plt.ylabel('Frequency')
plt.show()

