# -*- coding: utf-8 -*-
"""dsbda3SK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZS5ZWUgnfkeHi4Mx4qk0p79rG7LLM3o
"""

# 3 part 1
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
print("first few lines of dataset\n", df.head())

# Pclass is a categorical variable and Age is a quantitative variable

# using the groupby function to group the DataFrame df by the 'Pclass' column
#and then applying the describe method to get summary statistics for the 'Age' column within each group

grouped_stats = df.groupby('Pclass')
grouped_stats["Age"].describe()

mean_age_by_class = grouped_stats["Age"].mean().tolist()
print("mean age for each passenger class\n", mean_age_by_class)

# 3 part 2

import pandas as pd
column_names=["sepal_length","sepal_width", "petal_length", "petal_width","class"]
df  = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", names = column_names)


print("first few lines of dataset\n", df.head())

setosa_stats = df[df["class"] == "Iris-setosa"].describe()
print("Statastical data for setosa species\n", setosa_stats)

versicolor_stats = df[df["class"] == "Iris-versicolor"].describe()
print("Statastical data for versicolor species\n", versicolor_stats)

virginica_stats = df[df["class"] == "Iris-virginica"].describe()
print("Statastical data for verginica species\n", virginica_stats)

