# -*- coding: utf-8 -*-
"""dsbda1SKipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIzJflT97Jrtk9gsrB0F17XiExCgjgmS
"""



import pandas as pd
import numpy as np



url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

column_names=["sepal_length","sepal_width", "petal_length", "petal_width","class"]

df = pd.read_csv(url, names=column_names)
print(df.head())

print("informantion about dataset\n", df.info())

print("descriptive statastics of the dataset\n" , df.describe())

print("dimensions of the dataset",df.shape)

print("data types of variables\n", df.dtypes)

new_df  = pd.get_dummies(df,columns=['class'],drop_first = True)

print(new_df.head())

