# -*- coding: utf-8 -*-
"""dsbda10SK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PIAnRxgu0UibAZuX_h0AI_yV3lOh-eAu
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Download and load the Iris dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
column_names = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
iris = pd.read_csv(url, header=None, names=column_names)


# 1. List down the features and their types
feature_types = iris.dtypes
print("Features and their types:")
print(feature_types)

# 2. Create a histogram for each feature
plt.figure(figsize=(12, 8))
iris.drop("class", axis=1).hist(edgecolor="black", linewidth=1.2, bins=20, figsize=(12, 8))
plt.suptitle("Histograms for Each Feature", y=0.92)
plt.show()

# 3. Create a box plot for each feature
plt.figure(figsize=(12, 8))
sns.boxplot(data=iris.drop("class", axis=1), palette="Set2")
plt.title("Box Plots for Each Feature")
plt.show()

# 4. Compare distributions and identify outliers
plt.figure(figsize=(12, 8))
sns.boxplot(x="class", y="sepal_length", data=iris, hue="class", palette="Set2", legend=False)
plt.title("Box Plot for Sepal Length by Class")
plt.show()

#Analysis
# Based on the provided images, I can make the following conclusions:
# Image 1 (Histograms for Each Feature):

# sepal_length: The distribution appears roughly symmetric and unimodal, with most values concentrated around 5.5-6.5 cm.
# sepal_width: The distribution is slightly right-skewed, with a peak around 3.0-3.5 cm.
# petal_length: The distribution is bimodal, with peaks around 1.5 cm and 4.5 cm, indicating the presence of two distinct groups.
# petal_width: The distribution is heavily right-skewed, with most values concentrated near 0.0-1.0 cm and a long tail towards higher values.

# Image 2 (Box Plots for Each Feature):

# sepal_length: The box plot shows a relatively symmetric distribution with a few outliers on the higher end.
# sepal_width: The distribution is slightly skewed to the right, with a couple of outliers on the higher end.
# petal_length: The distribution is heavily right-skewed, with a significant number of outliers on the higher end, indicating the presence of distinct groups.
# petal_width: The distribution is heavily right-skewed, with multiple outliers on the higher end, further confirming the presence of distinct groups.

# Image 3 (Box Plot for Sepal Length by Class):
# This box plot compares the sepal length distributions across different classes (likely species) of the Iris dataset. There are clear differences in the median sepal lengths and interquartile ranges for each class, indicating distinct separations between the groups. The class represented by the orange box appears to have the longest sepal lengths, while the green class has the shortest sepal lengths.
# Overall, the histograms and box plots reveal distinct patterns and potential clustering in the Iris dataset, particularly evident in the petal length and petal width features. The sepal length box plot by class further highlights the separability of the classes based on this feature. These visualizations provide valuable insights into the data distributions and potential for classification or clustering tasks. CopySwhat are the circlesThe circles or dots represented in the box plots (Images 2 and 3) indicate potential outliers in the data.
# Specifically:
# Image 2 (Box Plots for Each Feature):
# ------------------------------
# dots
# For sepal_length, there are a few dots above the whiskers (lines extending from the box), indicating some data points with sepal lengths higher than the typical range for the majority of the data.
# For sepal_width, there are a couple of dots above the whiskers, representing outliers with higher sepal widths.
# For petal_length and petal_width, there are multiple dots above the whiskers, suggesting the presence of several outliers with larger petal dimensions compared to the bulk of the data.

# Image 3 (Box Plot for Sepal Length by Class):

# There is a single dot or circle above the whisker for the class represented by the blue box, indicating one or more outliers with higher sepal length values within that class.

# In box plots, these circles or dots mark individual data points that lie beyond the whiskers, which typically extend to 1.5 times the interquartile range (box height). Data points falling outside this range are considered potential outliers and are explicitly plotted to draw attention to their extreme values relative to the rest of the distribution.
# So in summary, the circles/dots represent outlier values that deviate significantly from the typical range of values observed for the respective features or classes shown in the box plots.